name = "CactusPlus"
license = "MIT"
licenselink = "https://github.com/OreChou/hugo-theme-cactus-plus/blob/main/LICENSE"
description = "A modern, clean Hugo theme for personal blogs with dark/light mode support"
homepage = "https://github.com/OreChou/hugo-theme-cactus-plus"
demosite = ""
tags = ["blog", "responsive", "clean", "dark-mode", "books"]
features = ["dark-light-mode", "books", "toc", "syntax-highlighting", "comments", "search"]
min_version = "0.100.0"

[author]
    name = "ORE CHOU"
    homepage = "https://github.com/OreChou"

# Forked from hugo-theme-bat
[original]
    author = "Zeran Wu"
    homepage = "https://github.com/monkeyWzr"
    repo = "https://github.com/monkeyWzr/hugo-theme-cactus"

# Originally based on hexo-theme-cactus
[source]
    author = "Pieter Robberechts"
    homepage = "https://github.com/probberechts"
    repo = "https://github.com/probberechts/hexo-theme-cactus"
